apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonflask-deployment
  labels:
    app: pythonflask
spec:
  replicas: 2      # e.g. 2
  selector:
    matchLabels:
      app: pythonflask
  template:
    metadata:
      labels:
        app: pythonflask
    spec:
      containers:
        - name: pythonflask
          image: saptarshi500/flaskapp:latest   # e.g. myrepo/myapp:latest
          ports:
            - containerPort: 5000   # e.g. 8080
          
